LINE2_DESKTOP_IMG = r"\src\img\line2_desktop_icon.png"
LINE2_MESSAGES_IMG = r"\src\img\line2_msg.png"
LINE2_BLUE_MESSAGES_IMG = r"\src\img\line2_blue_msg.png"
LINE2_NEW_MESSAGE_IMG = r"\src\img\line2_new_msg.png"
LINE2_CLOSE_MESSAGE_CHAT_IMG = r"\src\img\line2_close_msg_chat.png"
LINE2_TOO_MANY_MESSAGES_IMG = r"\src\img\line2_too_many_messages.png"
LINE2_TOO_MANY_MESSAGES_OK_BTN_IMG = r"\src\img\line2_too_many_messages_ok_btn.png"